// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://irxrkutczxskuqbpgntd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlyeHJrdXRjenhza3VxYnBnbnRkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxMjQ0ODYsImV4cCI6MjA3MjcwMDQ4Nn0.LcxoNeBFja_HRwmGmYAZddnl5EjDgKL9FgeZJZFUmP0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});